settings:
  APP_DISPLAY_NAME: Silent
  PRODUCTION_APP_NAME: Silent
  APP_GROUP_IDENTIFIER: group.com.cyber50defense.silent
  BASE_BUNDLE_IDENTIFIER: com.cybershield.silent
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 4GWA4C9LKJ
  IS_NIGHTLY_BUILD: false

  # Optional configuration to load accounts from Element Classic.
  CLASSIC_APP_GROUP_IDENTIFIER: group.com.cyber50defense.silent
  CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: im.vector.app.encryption-manager-service
  CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: "$(DEVELOPMENT_TEAM).$(BASE_BUNDLE_IDENTIFIER)"
  CLASSIC_APP_DEEP_LINK_URL: "element://open"
