//
// Copyright 2025 Element Creations Ltd.
// Copyright 2023-2025 New Vector Ltd.
//
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
// Please see LICENSE files in the repository root for full details.
//

import CompoundDesignTokens
import Synchronization
import UIKit

public extension UIColor {
    /// The colours used by Element as defined in Compound Design Tokens.
    nonisolated static let compound = CompoundUIColors()
}

/// The colours used by Element as defined in Compound Design Tokens.
/// This class contains only the colour tokens in a more usable form.
/// Since this can be used by attributed strings which may run in non isolated concurrent contexts,
/// The object needs to be nonisolated.
@Observable
@dynamicMemberLookup
public final nonisolated class CompoundUIColors: Sendable {
    /// The base colour tokens that form the palette of available colours.
    ///
    /// Normally these shouldn't be necessary, however in practice we may need
    /// access for temporary tokens while waiting for official ones to be formalised.
    private static let coreTokens = CompoundCoreUIColorTokens.self
    /// The main semantic tokens generated from the Style Dictionary.
    private let tokens = CompoundUIColorTokens()
    /// Runtime overrides for the `tokens` property.
    private let overrides = Mutex<[KeyPath<CompoundUIColorTokens, UIColor> & Sendable: UIColor]>(.init())

    init() {
        let silentBrandBlue = UIColor(red: 0.082, green: 0.333, blue: 0.878, alpha: 1.0)
        let silentBrandBluePressed = UIColor(red: 0.051, green: 0.247, blue: 0.706, alpha: 1.0)
        let silentBrandBlueSoft = UIColor(red: 0.91, green: 0.95, blue: 1.0, alpha: 1.0)

        overrides.withLock {
            $0[\.bgActionPrimaryRest] = silentBrandBlue
            $0[\.bgActionPrimaryPressed] = silentBrandBluePressed
            $0[\.bgAccentRest] = silentBrandBlue
            $0[\.bgAccentSelected] = silentBrandBlueSoft
            $0[\.iconAccentPrimary] = silentBrandBlue
            $0[\.iconAccentTertiary] = silentBrandBlue
            $0[\.textActionPrimary] = silentBrandBlue
            $0[\.textActionAccent] = silentBrandBlue
            $0[\.gradientActionStop1] = silentBrandBlue
            $0[\.gradientActionStop2] = silentBrandBlue
            $0[\.gradientActionStop3] = silentBrandBluePressed
            $0[\.gradientActionStop4] = silentBrandBluePressed
        }
    }

    public subscript(dynamicMember keyPath: KeyPath<CompoundUIColorTokens, UIColor> & Sendable) -> UIColor {
        overrides.withLock { $0[keyPath] } ?? tokens[keyPath: keyPath]
    }

    /// Customise the colour at the specified key path with the supplied colour.
    /// Supplying `nil` as the colour will remove any existing customisation.
    public func override(_ keyPath: KeyPath<CompoundUIColorTokens, UIColor> & Sendable, with color: UIColor?) {
        overrides.withLock { $0[keyPath] = color }
    }

    // MARK: - Awaiting Semantic Tokens

    // swiftformat:disable numberFormatting
    /// This token is a placeholder and hasn't been finalised.
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _bgCodeBlock: UIColor {
        CompoundUIColors.coreTokens.gray100
    }

    /// This token is a placeholder and hasn't been finalised.
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public let _bgSubtleSecondaryAlpha = coreTokens.alphaGray300
    // swiftformat:enable numberFormatting
}

private extension UITraitCollection {
    /// Whether or not the trait collection contains a `userInterfaceStyle` of `.light`.
    var isLight: Bool {
        userInterfaceStyle == .light
    }
}
